version: '3.8'

services:
  # Dịch vụ MySQL Database (KHÔNG CẦN PUSH - dùng image có sẵn)
  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lib_ai
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 3s
      start_period: 30s
    restart: always

  # Dịch vụ Backend AI (FastAPI) - Cần push
  backend-ai:
    build: ./backend-ai
    image: huy332005/backend-ai-service:1.0 # THÊM DÒNG NÀY
    container_name: backend_ai_service
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: mysql+pymysql://user_libai:huy@db:3306/lib_ai
    volumes:
      - ./backend-ai:/app
      - deepface_models_data:/root/.deepface/weights
    depends_on:
      db:
        condition: service_healthy
    restart: always

  # Dịch vụ Backend nghiệp vụ - Cần push
  backend:
    build: ./backend
    image: huy332005/backend-api-service:1.0 # THÊM DÒNG NÀY
    container_name: backend_service
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://admin_libai:huy1@db:3306/lib_ai
      AI_SERVICE_URL: http://backend-ai:8000
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    depends_on:
      db:
        condition: service_healthy
      backend-ai:
        condition: service_started
    restart: always

  # Dịch vụ Frontend User (React + Nginx) - Cần push
  frontend-user-react:
    build: ./frontend-user-react
    image: huy332005/frontend-user-react-app:1.0 # THÊM DÒNG NÀY
    container_name: frontend_user_react_app
    ports:
      - "8082:80"
    environment:
      REACT_APP_AI_SERVICE_URL: http://localhost:8001
      REACT_APP_BACKEND_API_URL: http://localhost:8000
    depends_on:
      backend-ai:
        condition: service_started
      backend:
        condition: service_started
    restart: always

  # Dịch vụ Frontend Admin - Cần push
  frontend-admin:
    build: ./frontend-admin
    image: huy332005/frontend-admin-app:1.0 # THÊM DÒNG NÀY
    container_name: frontend_admin_app
    ports:
      - "8083:80"
    environment:
      REACT_APP_BACKEND_API_URL: http://localhost:8000
    depends_on:
      backend:
        condition: service_started
    restart: always

volumes:
  mysql_data:
  backend_data:
  deepface_models_data: